= 4. Testing Workload Isolation with a Virtual Machine

Workload partitioning also applies to virtual machines managed by OpenShift Virtualization. Let's create a VM with 4 vCPUs and run the same stress test to verify this.

. *Access the VM and Run Stress Test:*
+
If you don't have `virtctl` installed, download it first:
+
[source,bash,role=execute]
----
DOMAIN=$(oc get ingress.config.openshift.io cluster -o jsonpath='{.spec.domain}')
wget --no-check-certificate https://hyperconverged-cluster-cli-download-openshift-cnv.${DOMAIN}/amd64/linux/virtctl.tar.gz
tar zvxf virtctl.tar.gz
mkdir -p ~/.local/bin/
mv virtctl ~/.local/bin/
----

. *Create a VM:* Use the OpenShift console or `virtctl` to create a virtual machine with 4 CPU cores in a project/namespace.
+
[NOTE]
====
First, let's create an SSH key pair. We will inject the public key into the VM using `cloud-init`. This will allow us to SSH into the VM without a password.
====

+
[source,bash,role=execute]
----
ssh-keygen -t rsa -f ~/.ssh/wlp_id_rsa -N ""
WLP_SSH_KEY=$(cat ~/.ssh/wlp_id_rsa.pub)

tee student-vm-ssh.yaml << EOF
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos9-student
  labels:
    app: centos9-student
spec:
  runStrategy: Manual
  dataVolumeTemplates:
    - metadata:
        name: centos-student-dv
      spec:
        sourceRef:
          kind: DataSource
          name: centos-stream9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos9-student
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        resources:
          # 2. Kubernetes 容器层面的资源锁定 (Resource Constraints)
          requests:
            memory: 2Gi
            cpu: 4        # 确保调度器预留 4 个核
          limits:
            memory: 2Gi   # 建议内存也做限制，防止被 OOM Kill
            cpu: 4        # 【关键】硬限制，超过 4 核的算力会被宿主机截断 (Throttled)
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: centos-student-dv
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: root
              password: redhat
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: False
              ssh_authorized_keys:
                - ${WLP_SSH_KEY}
EOF

oc apply -f student-vm-ssh.yaml

virtctl start centos9-student
----

+
Use `virtctl` to SSH into the VM and execute the `stress-ng` command.
+
[source,bash,role=execute]
----
virtctl ssh root@centos9-student --identity-file=~/.ssh/wlp_id_rsa
----
+
Once inside the VM, run the stress test:
+
[source,bash,role=execute]
----
dnf install -y /usr/bin/stress-ng

nohup stress-ng --cpu 4 --cpu-load 100 --temp-path /tmp &

exit
----


. Log in to the control plane node:
+
[source,bash,role=execute]
----
NODE_NAME=$(oc get nodes -o jsonpath='{.items[0].metadata.name}')

oc debug node/$NODE_NAME
----


. *Observe Host CPU Usage:*
+
Checking `top` on the host node will again show that the QEMU process for the VM is consuming CPU cycles exclusively from the isolated cores (20-23).
+
.Example `top` output
[source,text]
----
%Cpu0  :  8.1 us,  3.4 sy,  0.0 ni, 81.8 id,  0.3 wa,  1.7 hi,  4.7 si,  0.0 st
%Cpu1  :  7.8 us,  4.7 sy,  0.0 ni, 84.1 id,  0.0 wa,  1.4 hi,  2.0 si,  0.0 st
%Cpu2  :  7.7 us,  3.0 sy,  0.0 ni, 86.9 id,  0.3 wa,  1.3 hi,  0.7 si,  0.0 st
%Cpu3  :  9.4 us,  3.7 sy,  0.0 ni, 84.5 id,  0.0 wa,  1.7 hi,  0.7 si,  0.0 st
%Cpu4  :  7.4 us,  3.4 sy,  0.0 ni, 87.2 id,  0.0 wa,  1.3 hi,  0.7 si,  0.0 st
%Cpu5  :  7.0 us,  2.7 sy,  0.0 ni, 88.3 id,  0.0 wa,  1.3 hi,  0.3 si,  0.3 st
%Cpu6  :  6.4 us,  3.4 sy,  0.0 ni, 87.9 id,  0.3 wa,  1.7 hi,  0.3 si,  0.0 st
%Cpu7  :  7.4 us,  3.7 sy,  0.0 ni, 86.9 id,  0.0 wa,  1.7 hi,  0.3 si,  0.0 st
%Cpu8  :  6.7 us,  2.7 sy,  0.0 ni, 88.2 id,  0.0 wa,  1.7 hi,  0.7 si,  0.0 st
%Cpu9  :  7.7 us,  4.0 sy,  0.0 ni, 86.2 id,  0.3 wa,  1.3 hi,  0.3 si,  0.0 st
%Cpu10 :  7.1 us,  4.0 sy,  0.0 ni, 87.2 id,  0.0 wa,  1.3 hi,  0.3 si,  0.0 st
%Cpu11 :  8.7 us,  4.0 sy,  0.0 ni, 85.7 id,  0.0 wa,  1.3 hi,  0.3 si,  0.0 st
%Cpu12 :  9.6 us,  4.3 sy,  0.0 ni, 84.1 id,  0.0 wa,  1.7 hi,  0.3 si,  0.0 st
%Cpu13 :  8.7 us,  3.0 sy,  0.0 ni, 86.0 id,  0.3 wa,  1.3 hi,  0.7 si,  0.0 st
%Cpu14 :  8.7 us,  3.0 sy,  0.0 ni, 86.0 id,  0.0 wa,  1.7 hi,  0.7 si,  0.0 st
%Cpu15 :  6.7 us,  4.0 sy,  0.0 ni, 87.6 id,  0.0 wa,  1.3 hi,  0.3 si,  0.0 st
%Cpu16 : 99.7 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu17 : 99.7 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu18 : 99.7 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu19 : 99.7 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu20 :  0.7 us,  0.7 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu21 :  2.3 us,  1.6 sy,  0.0 ni, 95.4 id,  0.0 wa,  0.3 hi,  0.3 si,  0.0 st
%Cpu22 :  2.3 us,  1.3 sy,  0.0 ni, 96.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu23 :  1.0 us,  0.3 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu24 :  9.9 us,  1.3 sy,  0.0 ni, 88.4 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu25 :  0.3 us,  1.0 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu26 :  1.0 us,  0.7 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu27 :  0.7 us,  0.7 sy,  0.0 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu28 :  3.0 us,  0.7 sy,  0.0 ni, 96.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu29 :  1.3 us,  0.7 sy,  0.0 ni, 97.4 id,  0.0 wa,  0.3 hi,  0.3 si,  0.0 st
%Cpu30 :  2.0 us,  0.7 sy,  0.0 ni, 97.0 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu31 :  1.3 us,  0.7 sy,  0.0 ni, 97.4 id,  0.0 wa,  0.3 hi,  0.3 si,  0.0 st
----

. *Verifying VM Process CPU Affinity*
+
Finally, we can confirm the CPU affinity of the VM's QEMU process on the host node.
+
. Find the PID of the `qemu-kvm` process for the VM:
+
[source,bash,role=execute]
----
ps -ef | grep qemu-kvm
----
+
.Example `ps` output
[source,text]
----
107      1216721 1216582 99 15:03 ?        00:05:49 /usr/libexec/qemu-kvm -name guest=demo_centos9-student,.............
----
+
. Check its CPU affinity:
+
[source,bash,role=execute]
----
taskset -c -p $(pgrep -o qemu-kvm)
----
+
.Example `taskset` output
[source,text]
----
pid 1216721's current affinity list: 16-19
----

== cleanup

. delete the demo deployment
+
[source,bash,role-execute]
----
oc delete -f student-vm-ssh.yaml
----